name: "Check version and changelog"
description: "Make sure the version is bumped and it has a changelog entry"
inputs:
  actions_user_token:
    description: "User access token for sending errors as a PR message. This is not default repo token for actions, or else non-maintainers will not see the comments."
    required: false
    default: ""
  base_ref:
    description: "GitHub base_ref"
    required: true
    default: ""
outputs:
  package_version:
    description: "The package version"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.actions_user_token }}"
    - "${{ inputs.base_ref }}"
